# Generated by Django 5.0.6 on 2025-11-04 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categories_pk', models.AutoField(primary_key=True, serialize=False)),
                ('division', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('invoice_category', models.CharField(max_length=100)),
                ('order_in_list', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('contact_pk', models.AutoField(primary_key=True, serialize=False)),
                ('xero_contact_id', models.CharField(max_length=255)),
                ('division', models.IntegerField()),
                ('checked', models.IntegerField(default=0)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DesignCategories',
            fields=[
                ('design_category_pk', models.AutoField(primary_key=True, serialize=False)),
                ('design_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HC_claims',
            fields=[
                ('hc_claim_pk', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('display_id', models.IntegerField(blank=True, null=True)),
                ('invoicee', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hc_variation',
            fields=[
                ('hc_variation_pk', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Letterhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letterhead_path', models.FileField(upload_to='letterhead/')),
            ],
        ),
        migrations.CreateModel(
            name='Models_3d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='3d/')),
                ('filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Po_globals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('invoicee', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('project_address', models.CharField(max_length=255)),
                ('ABN', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('note1', models.CharField(max_length=1000)),
                ('note2', models.CharField(max_length=1000)),
                ('note3', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projects_pk', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=100)),
                ('xero_project_id', models.CharField(max_length=255, null=True)),
                ('xero_sales_account', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCategories',
            fields=[
                ('report_category_pk', models.AutoField(primary_key=True, serialize=False)),
                ('report_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SPVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('lot_size', models.CharField(max_length=255)),
                ('legal_owner', models.CharField(max_length=255)),
                ('folio_identifier', models.CharField(max_length=255)),
                ('bill_to', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('owner_address', models.CharField(max_length=255)),
                ('director_1', models.CharField(max_length=255)),
                ('director_2', models.CharField(max_length=255)),
                ('abn', models.CharField(max_length=255)),
                ('acn', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Costing',
            fields=[
                ('costing_pk', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=100)),
                ('xero_account_code', models.CharField(max_length=100)),
                ('contract_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uncommitted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uncommitted_notes', models.CharField(max_length=1000, null=True)),
                ('fixed_on_site', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sc_invoiced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sc_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categories')),
            ],
        ),
        migrations.CreateModel(
            name='HC_claim_allocations',
            fields=[
                ('hc_claim_allocations_pk', models.AutoField(primary_key=True, serialize=False)),
                ('contract_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('working_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('committed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uncommitted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixed_on_site', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixed_on_site_previous', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixed_on_site_this', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sc_invoiced_previous', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sc_invoiced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hc_claimed_previous', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hc_claimed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qs_claimed_previous', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qs_claimed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categories')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.costing')),
                ('hc_claim_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hc_claims')),
            ],
        ),
        migrations.CreateModel(
            name='Hc_variation_allocations',
            fields=[
                ('hc_variation_allocation_pk', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.costing')),
                ('hc_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hc_variation')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_pk', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_division', models.IntegerField()),
                ('invoice_status', models.IntegerField(default=0)),
                ('invoice_xero_id', models.CharField(max_length=255, null=True)),
                ('supplier_invoice_number', models.CharField(max_length=255)),
                ('invoice_date', models.DateField()),
                ('invoice_due_date', models.DateField()),
                ('total_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(upload_to='invoices/')),
                ('invoice_type', models.IntegerField(choices=[(2, 'Progress Claim'), (1, 'Direct Cost')], default=0)),
                ('associated_hc_claim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hc_claims')),
                ('contact_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_allocations',
            fields=[
                ('invoice_allocations_pk', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(max_length=1000, null=True)),
                ('allocation_type', models.IntegerField(choices=[(0, 'as per invoice_type'), (1, 'direct cost in progress claim')], default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.costing')),
                ('invoice_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_allocations', to='core.invoices')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPdfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='plans/')),
                ('plan_number', models.CharField(max_length=255)),
                ('rev_number', models.CharField(max_length=255)),
                ('design_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.designcategories')),
            ],
        ),
        migrations.CreateModel(
            name='Po_orders',
            fields=[
                ('po_order_pk', models.AutoField(primary_key=True, serialize=False)),
                ('po_sent', models.BooleanField(default=False)),
                ('po_note_1', models.CharField(max_length=1000)),
                ('po_note_2', models.CharField(max_length=1000)),
                ('po_note_3', models.CharField(max_length=1000)),
                ('po_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('quotes_pk', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_quote_number', models.CharField(max_length=255)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(null=True, upload_to='pdfs/')),
                ('contact_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Quote_allocations',
            fields=[
                ('quote_allocations_pk', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(max_length=1000, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.costing')),
                ('quotes_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_allocations', to='core.quotes')),
            ],
        ),
        migrations.CreateModel(
            name='Po_order_detail',
            fields=[
                ('po_order_detail_pk', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variation_note', models.CharField(max_length=1000, null=True)),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.costing')),
                ('po_order_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.po_orders')),
                ('quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.quotes')),
            ],
        ),
        migrations.CreateModel(
            name='ReportPdfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('report_reference', models.CharField(max_length=255)),
                ('report_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reportcategories')),
            ],
        ),
    ]
