# Generated by Django 5.0.6 on 2025-11-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_type',
            field=models.CharField(choices=[('general', 'General'), ('development', 'Development'), ('construction', 'Construction'), ('precast', 'Precast'), ('pods', 'Pods')], default='general', help_text='Type of project determines which app features are available', max_length=20),
        ),
    ]
