# Generated by Django 5.0.6 on 2025-11-08 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_project_type_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroInstances',
            fields=[
                ('xero_instance_pk', models.AutoField(primary_key=True, serialize=False)),
                ('xero_name', models.CharField(max_length=255)),
                ('xero_client_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='xero_project_id',
        ),
        migrations.AddField(
            model_name='projects',
            name='xero_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.xeroinstances'),
        ),
    ]
