# Generated by Django 5.0.6 on 2025-11-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_xeroinstances_remove_projects_xero_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroinstances',
            name='xero_client_secret_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
