# Generated by Django 5.0.6 on 2025-11-09 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_xeroinstances_xero_client_secret_encrypted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='contact_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='contacts',
            name='bank_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='bank_details_verified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contacts',
            name='status',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='xero_instance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.xeroinstances'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacts',
            name='division',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
