# Generated by Django 5.0.6 on 2025-11-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_contact_email_contacts_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroinstances',
            name='oauth_access_token_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xeroinstances',
            name='oauth_refresh_token_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xeroinstances',
            name='oauth_tenant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xeroinstances',
            name='oauth_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
