# Generated by Django 5.0.6 on 2025-11-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_xeroinstances_oauth_access_token_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
