# Generated by Django 5.0.6 on 2025-11-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contacts_tax_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='bank_bsb',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
