# Generated by Django 5.0.6 on 2025-11-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contacts_bank_account_number_contacts_bank_bsb'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='verified_bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='verified_bank_bsb',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='verified_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='verified_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='verified_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='verified_tax_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
