# Generated by Django 5.0.6 on 2025-11-15 07:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_verified_contact_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.EmailField(max_length=255)),
                ('to_address', models.EmailField(max_length=255)),
                ('cc_address', models.TextField(blank=True, default='')),
                ('subject', models.CharField(max_length=500)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('s3_bucket', models.CharField(max_length=100)),
                ('s3_key', models.CharField(max_length=500)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_notes', models.TextField(blank=True, default='')),
                ('email_type', models.CharField(choices=[('bill', 'Bill/Invoice'), ('quote', 'Quote'), ('receipt', 'Receipt'), ('other', 'Other')], default='other', max_length=50)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['-received_at'], name='core_receiv_receive_1aca60_idx'), models.Index(fields=['from_address'], name='core_receiv_from_ad_50f7e7_idx'), models.Index(fields=['message_id'], name='core_receiv_message_26e362_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.IntegerField()),
                ('s3_bucket', models.CharField(max_length=100)),
                ('s3_key', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.receivedemail')),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
    ]
