# Generated by Django 5.0.6 on 2025-11-15 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_invoices_email_linking'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='xero_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.xeroinstances'),
        ),
    ]
