# Generated by Django 5.0.6 on 2025-11-17 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_xero_instance_to_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroAccounts',
            fields=[
                ('xero_account_pk', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('account_code', models.CharField(max_length=50)),
                ('account_id', models.CharField(max_length=255)),
                ('account_status', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('xero_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xero_accounts', to='core.xeroinstances')),
            ],
            options={
                'verbose_name': 'Xero Account',
                'verbose_name_plural': 'Xero Accounts',
                'db_table': 'xero_accounts',
                'unique_together': {('xero_instance', 'account_code')},
            },
        ),
        migrations.CreateModel(
            name='XeroDivisions',
            fields=[
                ('xero_division_pk', models.AutoField(primary_key=True, serialize=False)),
                ('tracking_category_name', models.CharField(max_length=255)),
                ('tracking_category_id', models.CharField(max_length=255)),
                ('division_name', models.CharField(max_length=255)),
                ('division_id', models.CharField(max_length=255)),
                ('division_status', models.CharField(blank=True, max_length=50, null=True)),
                ('xero_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='core.xeroinstances')),
            ],
            options={
                'verbose_name': 'Xero Division',
                'verbose_name_plural': 'Xero Divisions',
                'db_table': 'xero_divisions',
                'unique_together': {('xero_instance', 'division_id')},
            },
        ),
    ]
