# Generated by Django 5.0.6 on 2025-11-17 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_xeroaccounts_xerodivisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_allocations',
            name='xero_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_allocations', to='core.xeroaccounts'),
        ),
        migrations.AddField(
            model_name='invoice_allocations',
            name='xero_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_allocations', to='core.xerodivisions'),
        ),
        migrations.AlterField(
            model_name='invoice_allocations',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.costing'),
        ),
        migrations.AlterField(
            model_name='invoice_allocations',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
