# Generated by Django 5.0.6 on 2025-11-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_invoice_allocations_xero_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_allocations',
            name='xero_division',
        ),
        migrations.DeleteModel(
            name='XeroDivisions',
        ),
    ]
