# Generated by Django 5.0.6 on 2025-11-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_xero_divisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='project_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='xero_sales_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
