# Generated by Django 5.0.6 on 2025-11-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_projects_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='archived',
            field=models.IntegerField(default=0),
        ),
    ]
