# Generated by Django 5.0.6 on 2025-11-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_projects_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_status',
            field=models.IntegerField(default=0),
        ),
    ]
