# Generated by Django 5.0.6 on 2025-11-22 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_projects_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projects'),
        ),
        migrations.AddField(
            model_name='costing',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projects'),
        ),
    ]
