# Generated by Django 5.0.6 on 2025-11-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_categories_project_costing_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='order_in_list',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
    ]
