# Generated by Django 5.0.6 on 2025-11-22 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_costing_order_in_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.projects'),
        ),
    ]
