# Generated by Django 5.0.6 on 2025-11-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_document_folders_document_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
