# Generated by Django 5.0.6 on 2025-11-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_contact_person_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
