# Generated by Django 5.0.6 on 2025-11-28 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_contacts_first_name_contacts_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='po_orders',
            name='po_note_1',
        ),
        migrations.RemoveField(
            model_name='po_orders',
            name='po_note_2',
        ),
        migrations.RemoveField(
            model_name='po_orders',
            name='po_note_3',
        ),
        migrations.AddField(
            model_name='po_orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='po_orders',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projects'),
        ),
        migrations.AddField(
            model_name='po_orders',
            name='unique_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
