# Generated by Django 5.0.6 on 2025-11-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_po_orders_po_note_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='po_orders',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='po_pdfs/'),
        ),
    ]
