# Generated by Django 5.0.6 on 2025-11-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_po_orders_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='contracts_admin_emails',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='manager_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
