# Generated by Django 5.0.6 on 2025-11-29 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_uncommitted_costing_uncommitted_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costing',
            old_name='uncommitted_unit',
            new_name='unit',
        ),
    ]
