# Generated by Django 5.0.6 on 2025-11-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_uncommitted_unit_costing_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('unit_pk', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=50, unique=True)),
                ('order_in_list', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Units',
                'ordering': ['order_in_list'],
            },
        ),
    ]
