# Generated by Django 5.0.6 on 2025-11-30 21:26

from django.db import migrations


def populate_units_from_existing_data(apps, schema_editor):
    """
    Create Units records for all unique unit values found in existing Costing records.
    This must run BEFORE changing Costing.unit from CharField to ForeignKey.
    """
    Costing = apps.get_model('core', 'Costing')
    Units = apps.get_model('core', 'Units')
    
    # Get all unique unit values from existing Costings (excluding None/empty)
    existing_units = Costing.objects.exclude(unit__isnull=True).exclude(unit='').values_list('unit', flat=True).distinct()
    
    # Create Units records for each unique unit value
    for idx, unit_name in enumerate(sorted(set(existing_units)), start=1):
        # Check if unit already exists
        unit, created = Units.objects.get_or_create(
            unit_name=unit_name,
            defaults={'order_in_list': idx}
        )
        if created:
            print(f"Created Unit: {unit_name} (order: {idx})")
    
    print(f"Ensured {len(set(existing_units))} units exist in database")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_units'),
    ]

    operations = [
        migrations.RunPython(populate_units_from_existing_data, reverse_code=migrations.RunPython.noop),
    ]
