# Generated by Django 5.0.6 on 2025-11-30 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_populate_units_from_existing_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='unit_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costings_new', to='core.units'),
        ),
    ]
