# Generated by Django 5.0.6 on 2025-11-30 21:32

from django.db import migrations


def migrate_unit_to_unit_fk(apps, schema_editor):
    """
    Copy data from unit (CharField) to unit_fk (ForeignKey).
    Match unit names to Units.unit_name and set unit_fk to the corresponding Units object.
    """
    Costing = apps.get_model('core', 'Costing')
    Units = apps.get_model('core', 'Units')
    
    # Get all costings with a unit value
    costings_with_unit = Costing.objects.exclude(unit__isnull=True).exclude(unit='')
    
    updated_count = 0
    for costing in costings_with_unit:
        try:
            # Find the matching Units record by unit_name
            unit_obj = Units.objects.get(unit_name=costing.unit)
            costing.unit_fk = unit_obj
            costing.save(update_fields=['unit_fk'])
            updated_count += 1
        except Units.DoesNotExist:
            print(f"Warning: No Unit found for name '{costing.unit}' in Costing {costing.costing_pk}")
    
    print(f"Migrated {updated_count} Costing records to use unit_fk")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_costing_unit_fk'),
    ]

    operations = [
        migrations.RunPython(migrate_unit_to_unit_fk, reverse_code=migrations.RunPython.noop),
    ]
