# Generated by Django 5.0.6 on 2025-11-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_migrate_unit_to_unit_fk'),
    ]

    operations = [
        # Step 1: Rename the old unit (CharField) to unit_old
        migrations.RenameField(
            model_name='costing',
            old_name='unit',
            new_name='unit_old',
        ),
        # Step 2: Rename unit_fk (ForeignKey) to unit
        migrations.RenameField(
            model_name='costing',
            old_name='unit_fk',
            new_name='unit',
        ),
        # Step 3: Remove the old CharField field
        migrations.RemoveField(
            model_name='costing',
            name='unit_old',
        ),
    ]
