# Generated by Django 5.0.6 on 2025-12-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_timestamps_to_all_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costing',
            options={'ordering': ['category__order_in_list', 'order_in_list']},
        ),
        migrations.AlterModelOptions(
            name='invoices',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='costing',
            index=models.Index(fields=['project', 'category'], name='core_costin_project_042211_idx'),
        ),
        migrations.AddIndex(
            model_name='costing',
            index=models.Index(fields=['category'], name='core_costin_categor_641f85_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice_allocations',
            index=models.Index(fields=['invoice_pk'], name='core_invoic_invoice_be5941_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice_allocations',
            index=models.Index(fields=['item'], name='core_invoic_item_id_f1fedc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoices',
            index=models.Index(fields=['invoice_status'], name='core_invoic_invoice_4f6978_idx'),
        ),
        migrations.AddIndex(
            model_name='invoices',
            index=models.Index(fields=['contact_pk'], name='core_invoic_contact_73a2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoices',
            index=models.Index(fields=['project'], name='core_invoic_project_4129be_idx'),
        ),
        migrations.AddIndex(
            model_name='invoices',
            index=models.Index(fields=['invoice_type'], name='core_invoic_invoice_841f06_idx'),
        ),
        migrations.AddIndex(
            model_name='invoices',
            index=models.Index(fields=['-created_at'], name='core_invoic_created_7395ad_idx'),
        ),
        migrations.AddIndex(
            model_name='quote_allocations',
            index=models.Index(fields=['quotes_pk'], name='core_quote__quotes__69953a_idx'),
        ),
        migrations.AddIndex(
            model_name='quote_allocations',
            index=models.Index(fields=['item'], name='core_quote__item_id_5efb85_idx'),
        ),
    ]
