# Generated by Django 5.0.6 on 2026-01-10 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_add_xero_tracking_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='associated_hc_claim',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='contact_pk',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='email_attachment',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='project',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='received_email',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='xero_instance',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='division',
        ),
        migrations.AddField(
            model_name='costing',
            name='xero_tracking_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('bill_pk', models.AutoField(primary_key=True, serialize=False)),
                ('bill_status', models.IntegerField(default=0)),
                ('bill_xero_id', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_bill_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('bill_due_date', models.DateField(blank=True, null=True)),
                ('total_net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='bills/')),
                ('bill_type', models.IntegerField(choices=[(2, 'Progress Claim'), (1, 'Direct Cost')], default=0)),
                ('auto_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('associated_hc_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hc_claims')),
                ('contact_pk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contacts')),
                ('email_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='core.emailattachment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='core.projects')),
                ('received_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='core.receivedemail')),
                ('xero_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='core.xeroinstances')),
            ],
            options={
                'db_table': 'core_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bill_allocations',
            fields=[
                ('bill_allocation_pk', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('allocation_type', models.IntegerField(choices=[(0, 'as per bill_type'), (1, 'direct cost in progress claim')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.costing')),
                ('xero_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_allocations', to='core.xeroaccounts')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_allocations', to='core.bills')),
            ],
            options={
                'db_table': 'core_invoice_allocations',
            },
        ),
        migrations.DeleteModel(
            name='Invoice_allocations',
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
        migrations.AddIndex(
            model_name='bills',
            index=models.Index(fields=['bill_status'], name='core_invoic_bill_st_452040_idx'),
        ),
        migrations.AddIndex(
            model_name='bills',
            index=models.Index(fields=['contact_pk'], name='core_invoic_contact_73a2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='bills',
            index=models.Index(fields=['project'], name='core_invoic_project_4129be_idx'),
        ),
        migrations.AddIndex(
            model_name='bills',
            index=models.Index(fields=['bill_type'], name='core_invoic_bill_ty_7de2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='bills',
            index=models.Index(fields=['-created_at'], name='core_invoic_created_7395ad_idx'),
        ),
        migrations.AddIndex(
            model_name='bill_allocations',
            index=models.Index(fields=['bill'], name='core_invoic_bill_id_ed2199_idx'),
        ),
        migrations.AddIndex(
            model_name='bill_allocations',
            index=models.Index(fields=['item'], name='core_invoic_item_id_f1fedc_idx'),
        ),
    ]
