# Generated by Django 5.0.6 on 2026-01-10 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_projects_project_type_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='division',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projecttypes',
            name='archived',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_type',
            field=models.ForeignKey(blank=True, help_text='Type of project determines which app features are available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_by_type', to='core.projecttypes'),
        ),
    ]
