# Generated by Django 5.0.6 on 2026-01-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_add_archived_to_projecttypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='xero_tracking_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
