# Generated by Django 5.0.6 on 2026-01-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_add_xero_tracking_category_to_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttypes',
            name='rates_based',
            field=models.IntegerField(default=0),
        ),
    ]
