# Generated by Django 5.0.6 on 2026-01-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_rates_based_to_project_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_status',
            field=models.IntegerField(default=1),
        ),
    ]
