# Generated by Django 5.0.6 on 2026-01-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_update_project_status_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='tender_or_execution',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotes',
            name='tender_or_execution',
            field=models.IntegerField(default=1),
        ),
    ]
