# Generated by Django 5.0.6 on 2026-01-11 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_costing_tender_or_execution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_allocations',
            name='tracking_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_allocations', to='core.xerotrackingcategories'),
        ),
    ]
