# Generated by Django 5.0.6 on 2026-01-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_bill_allocations_tracking_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroinstances',
            name='staff_hours_tracking',
            field=models.IntegerField(default=0),
        ),
    ]
