# Generated by Django 5.0.6 on 2026-01-25 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_xeroinstances_staff_hours_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHolidayCalendar',
            fields=[
                ('calendar_pk', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('WA', 'Western Australia'), ('TAS', 'Tasmania'), ('NT', 'Northern Territory'), ('ACT', 'Australian Capital Territory'), ('NAT', 'National')], default='NAT', max_length=3)),
                ('is_default', models.IntegerField(default=0)),
                ('archived', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Public Holiday Calendar',
                'verbose_name_plural': 'Public Holiday Calendars',
                'db_table': 'public_holiday_calendars',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('holiday_pk', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.publicholidaycalendar')),
            ],
            options={
                'verbose_name': 'Public Holiday',
                'verbose_name_plural': 'Public Holidays',
                'db_table': 'public_holidays',
                'ordering': ['date'],
                'unique_together': {('calendar', 'date')},
            },
        ),
    ]
