# Generated by Django 5.0.6 on 2026-01-26 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_publicholidaycalendar_publicholiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_pk', models.AutoField(primary_key=True, serialize=False)),
                ('xero_employee_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('xero_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.xeroinstances')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['name'],
                'unique_together': {('xero_instance', 'xero_employee_id')},
            },
        ),
        migrations.CreateModel(
            name='EmployeePayRate',
            fields=[
                ('payrate_pk', models.AutoField(primary_key=True, serialize=False)),
                ('effective_date', models.DateField()),
                ('earnings_rate_id', models.CharField(blank=True, max_length=100, null=True)),
                ('earnings_rate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rate_per_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('units_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('annual_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pay_basis', models.CharField(choices=[('HOURLY', 'Hourly'), ('SALARY', 'Salary')], default='HOURLY', max_length=10)),
                ('is_ordinary_rate', models.BooleanField(default=False)),
                ('rate_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_rates', to='core.employee')),
            ],
            options={
                'verbose_name': 'Employee Pay Rate',
                'verbose_name_plural': 'Employee Pay Rates',
                'db_table': 'employee_pay_rates',
                'ordering': ['employee', '-effective_date'],
                'indexes': [models.Index(fields=['employee', 'effective_date'], name='employee_pa_employe_278a5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffHours',
            fields=[
                ('staff_hours_pk', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='core.employee')),
            ],
            options={
                'verbose_name': 'Staff Hours',
                'verbose_name_plural': 'Staff Hours',
                'db_table': 'staff_hours',
                'ordering': ['-date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
