# Generated by Django 5.0.6 on 2026-01-26 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_employee_employeepayrate_staffhours'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffHoursAllocations',
            fields=[
                ('allocation_pk', models.AutoField(primary_key=True, serialize=False)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_allocations', to='core.costing')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_allocations', to='core.projects')),
                ('staff_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.staffhours')),
            ],
            options={
                'verbose_name': 'Staff Hours Allocation',
                'verbose_name_plural': 'Staff Hours Allocations',
                'db_table': 'staff_hours_allocations',
                'ordering': ['staff_hours', 'project'],
            },
        ),
    ]
