# Generated by Django 5.0.6 on 2026-01-28 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_staffhoursallocations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffhoursallocations',
            options={'ordering': ['staff_hours', 'allocation_type', 'project'], 'verbose_name': 'Staff Hours Allocation', 'verbose_name_plural': 'Staff Hours Allocations'},
        ),
        migrations.AddField(
            model_name='staffhoursallocations',
            name='allocation_type',
            field=models.IntegerField(choices=[(1, 'Project'), (2, 'Unchargeable'), (3, 'Other Chargeable')], default=1, help_text='1=Project, 2=Unchargeable, 3=Other Chargeable'),
        ),
        migrations.AddField(
            model_name='staffhoursallocations',
            name='note',
            field=models.CharField(blank=True, help_text='Required for Unchargeable and Other Chargeable allocations', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staffhoursallocations',
            name='costing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_allocations', to='core.costing'),
        ),
        migrations.AlterField(
            model_name='staffhoursallocations',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_allocations', to='core.projects'),
        ),
    ]
