# Generated by Django 5.0.6 on 2026-01-30 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_stocktakeallocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocktakeOpeningBalance',
            fields=[
                ('opening_balance_pk', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=5, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=5, max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'stocktake_opening_balances',
            },
        ),
        migrations.CreateModel(
            name='StocktakeSnap',
            fields=[
                ('snap_pk', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('costing_method', models.CharField(choices=[('FIFO', 'First In First Out'), ('LIFO', 'Last In First Out'), ('AVG', 'Weighted Average')], default='FIFO', max_length=10)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Finalised'), (2, 'Sent to Xero')], default=0)),
                ('xero_journal_id', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'stocktake_snaps',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeSnapAllocation',
            fields=[
                ('snap_allocation_pk', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=5, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=5, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'stocktake_snap_allocations',
            },
        ),
        migrations.CreateModel(
            name='StocktakeSnapItem',
            fields=[
                ('snap_item_pk', models.AutoField(primary_key=True, serialize=False)),
                ('book_qty', models.DecimalField(decimal_places=5, max_digits=15)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('variance_qty', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'stocktake_snap_items',
            },
        ),
        migrations.RenameIndex(
            model_name='stocktakeallocations',
            new_name='stocktake_a_bill_id_71c1d7_idx',
            old_name='stocktake_a_bill_id_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktakeallocations',
            new_name='stocktake_a_item_id_79d7e9_idx',
            old_name='stocktake_a_item_id_d4e5f6_idx',
        ),
        migrations.AddField(
            model_name='stocktakeopeningbalance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktake_opening_balances', to='core.costing'),
        ),
        migrations.AddIndex(
            model_name='stocktakesnap',
            index=models.Index(fields=['date'], name='stocktake_s_date_6f80c5_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktakesnap',
            index=models.Index(fields=['status'], name='stocktake_s_status_fbf430_idx'),
        ),
        migrations.AddField(
            model_name='stocktakesnapallocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktake_snap_allocations', to='core.projects'),
        ),
        migrations.AddField(
            model_name='stocktakesnapitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktake_snap_items', to='core.costing'),
        ),
        migrations.AddField(
            model_name='stocktakesnapitem',
            name='snap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snap_items', to='core.stocktakesnap'),
        ),
        migrations.AddField(
            model_name='stocktakesnapallocation',
            name='snap_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.stocktakesnapitem'),
        ),
        migrations.AddIndex(
            model_name='stocktakeopeningbalance',
            index=models.Index(fields=['item'], name='stocktake_o_item_id_a44f82_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktakeopeningbalance',
            index=models.Index(fields=['date'], name='stocktake_o_date_a58ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktakesnapitem',
            index=models.Index(fields=['snap'], name='stocktake_s_snap_id_492e90_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktakesnapitem',
            index=models.Index(fields=['item'], name='stocktake_s_item_id_8d948a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktakesnapitem',
            unique_together={('snap', 'item')},
        ),
        migrations.AddIndex(
            model_name='stocktakesnapallocation',
            index=models.Index(fields=['snap_item'], name='stocktake_s_snap_it_033e22_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktakesnapallocation',
            index=models.Index(fields=['project'], name='stocktake_s_project_c277d6_idx'),
        ),
    ]
