# Generated by Django 5.0.6 on 2026-02-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_stocktakeopeningbalance_stocktakesnap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroinstances',
            name='stocktake',
            field=models.IntegerField(default=0),
        ),
    ]
