# Generated by Django 5.0.6 on 2026-03-03 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_add_fx_fields_to_bills'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bills',
            new_name='core_invoic_currenc_c66a73_idx',
            old_name='core_invoic_currenc_fx_idx',
        ),
        migrations.AddField(
            model_name='xeroinstances',
            name='xero_stocktake_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktake_xero_instances', to='core.xeroaccounts'),
        ),
    ]
