# Generated by Django 5.0.6 on 2026-03-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_add_xero_stocktake_account_to_xeroinstances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill_allocations',
            name='tracking_category',
        ),
        migrations.RemoveField(
            model_name='costing',
            name='xero_tracking_category',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='xero_tracking_category',
        ),
        migrations.DeleteModel(
            name='XeroTrackingCategories',
        ),
    ]
