# Generated by Django 5.0.6 on 2026-03-28 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_xero_tracking_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroinstances',
            name='xero_stocktake_writeoffs_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktake_writeoffs_xero_instances', to='core.xeroaccounts'),
        ),
    ]
