# Generated by Django 5.0.6 on 2026-03-28 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_add_stocktake_writeoffs_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktakesnapallocation',
            name='is_writeoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktakesnapallocation',
            name='writeoff_xero_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktake_writeoff_allocations', to='core.xeroinstances'),
        ),
        migrations.AlterField(
            model_name='stocktakesnapallocation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocktake_snap_allocations', to='core.projects'),
        ),
    ]
