# Generated by Django 5.0.6 on 2026-05-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_renumber_hc_claims_display_id_per_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffhoursallocations',
            name='allocation_type',
            field=models.IntegerField(choices=[(1, 'Project'), (2, 'Unchargeable'), (3, 'Other Chargeable'), (4, 'R&D')], default=1, help_text='1=Project, 2=Unchargeable, 3=Other Chargeable, 4=R&D'),
        ),
        migrations.AlterField(
            model_name='staffhoursallocations',
            name='note',
            field=models.CharField(blank=True, help_text='Required for Unchargeable, Other Chargeable, and R&D allocations', max_length=500, null=True),
        ),
    ]
