# Generated by Django 5.0.6 on 2026-05-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_staffhoursallocations_add_rd_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttypes',
            name='qs',
            field=models.BooleanField(default=True),
        ),
    ]
