# Generated by Django 4.2.27 on 2026-06-08 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_projects_tender_substatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressClaimDocs',
            fields=[
                ('claim_docs_pk', models.AutoField(primary_key=True, serialize=False)),
                ('workers_comp_coc', models.FileField(blank=True, null=True, upload_to='claim_docs/workers_comp/')),
                ('declaration_data', models.JSONField(blank=True, null=True)),
                ('declaration_pdf', models.FileField(blank=True, null=True, upload_to='claim_docs/declarations/')),
                ('declaration_signed_name', models.CharField(blank=True, default='', max_length=200)),
                ('declaration_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim_docs', to='core.bills')),
            ],
        ),
    ]
