# Generated by Django 4.2.3 on 2024-04-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categories_pk', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('order_in_list', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
