# Generated by Django 4.2.3 on 2024-04-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projects_pk', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=100)),
            ],
        ),
    ]
