# Generated by Django 4.2.3 on 2024-04-14 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('contact_pk', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('quotes_pk', models.AutoField(primary_key=True, serialize=False)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('contact_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contacts')),
            ],
        ),
    ]
