# Generated by Django 4.2.3 on 2024-04-14 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contacts_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costing',
            fields=[
                ('costing_pk', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=100)),
                ('contract_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uncommitted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sc_invoiced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sc_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories')),
            ],
        ),
    ]
