# Generated by Django 4.2.3 on 2024-04-16 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_costing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote_allocations',
            fields=[
                ('quote_allocations_pk', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.costing')),
                ('quotes_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quotes')),
            ],
        ),
    ]
