# Generated by Django 4.2.3 on 2024-04-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_quote_allocations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costing',
            name='notes',
        ),
    ]
