# Generated by Django 4.2.3 on 2024-05-18 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_costing_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignCategories',
            fields=[
                ('design_category_pk', models.AutoField(primary_key=True, serialize=False)),
                ('design_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanPdfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='plans/')),
                ('plan_number', models.IntegerField()),
                ('design_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.designcategories')),
            ],
        ),
    ]
