# Generated by Django 4.2.3 on 2024-05-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_designcategories_planpdfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpdfs',
            name='rev_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
