# Generated by Django 4.2.3 on 2024-05-20 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_planpdfs_plan_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategories',
            fields=[
                ('report_category_pk', models.AutoField(primary_key=True, serialize=False)),
                ('report_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReportPdfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('report_reference', models.CharField(max_length=255)),
                ('report_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reportcategories')),
            ],
        ),
    ]
