# Generated by Django 4.2.3 on 2024-05-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_reportcategories_reportpdfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models_3d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='3d/')),
                ('filename', models.CharField(max_length=255)),
            ],
        ),
    ]
