# Generated by Django 4.2.3 on 2024-06-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_models_3d'),
    ]

    operations = [
        migrations.CreateModel(
            name='Po_globals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('invoicee', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('ABN', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('note1', models.CharField(max_length=1000)),
                ('note2', models.CharField(max_length=1000)),
                ('note3', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Po_orders',
            fields=[
                ('po_order_pk', models.AutoField(primary_key=True, serialize=False)),
                ('po_note_1', models.CharField(max_length=1000)),
                ('po_note_2', models.CharField(max_length=1000)),
                ('po_note_3', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Po_order_detail',
            fields=[
                ('po_order_detail_pk', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.costing')),
                ('po_order_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.po_orders')),
                ('quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quotes')),
            ],
        ),
    ]
