# Generated by Django 5.0.6 on 2024-06-06 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_po_globals_po_orders_po_order_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='po_orders',
            name='po_supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.contacts'),
            preserve_default=False,
        ),
    ]
