# Generated by Django 5.0.6 on 2024-06-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_po_orders_po_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='po_order_detail',
            name='variation_note',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
