# Generated by Django 5.0.6 on 2024-06-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_po_order_detail_variation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po_order_detail',
            name='variation_note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
