# Generated by Django 5.0.6 on 2024-06-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_po_order_detail_variation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='po_globals',
            name='project_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
