# Generated by Django 5.0.6 on 2024-06-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_po_globals_project_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='supplier_quote_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
