# Generated by Django 5.0.6 on 2024-06-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_quotes_supplier_quote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='contact_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
