# Generated by Django 5.0.6 on 2024-06-22 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_po_orders_po_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('order_in_list', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hc_claims',
            fields=[
                ('hc_claim', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Build_costing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=100)),
                ('contract_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uncommitted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('complete_on_site', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hc_next_claim', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hc_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sc_invoiced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sc_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('claim', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs')),
                ('sent_to_xero', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Claim_allocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.costing')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.claims')),
            ],
        ),
        migrations.CreateModel(
            name='Committed_quotes',
            fields=[
                ('quote', models.AutoField(primary_key=True, serialize=False)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('contact_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Committed_allocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.costing')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.committed_quotes')),
            ],
        ),
        migrations.CreateModel(
            name='Hc_claim_lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hc_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hc_claims')),
            ],
        ),
    ]
