# Generated by Django 5.0.6 on 2024-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_build_costing_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committed_quotes',
            name='supplier_quote_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
