# Generated by Django 5.0.6 on 2024-06-27 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_committed_quotes_supplier_quote_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build_po_orders',
            fields=[
                ('po_order_pk', models.AutoField(primary_key=True, serialize=False)),
                ('po_sent', models.BooleanField(default=False)),
                ('po_note_1', models.CharField(max_length=1000)),
                ('po_note_2', models.CharField(max_length=1000)),
                ('po_note_3', models.CharField(max_length=1000)),
                ('po_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Build_po_order_detail',
            fields=[
                ('po_order_detail_pk', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variation_note', models.CharField(max_length=1000, null=True)),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.build_costing')),
                ('quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.committed_quotes')),
                ('po_order_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.build_po_orders')),
            ],
        ),
    ]
