# Generated by Django 5.0.6 on 2024-06-29 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_build_po_orders_build_po_order_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build_costing',
            old_name='id',
            new_name='costing_pk',
        ),
    ]
