# Generated by Django 5.0.6 on 2024-06-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_id_build_costing_costing_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='division',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='division',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
