# Generated by Django 5.0.6 on 2024-07-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_spvdata_remove_build_costing_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letterhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letterhead_path', models.FileField(upload_to='letterhead')),
            ],
        ),
    ]
