# Generated by Django 5.0.6 on 2024-07-03 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_letterhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterhead',
            name='letterhead_path',
            field=models.FileField(upload_to='letterhead/'),
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_pk', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_invoice_number', models.CharField(max_length=255)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(upload_to='invoices/')),
                ('contact_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contacts')),
            ],
        ),
    ]
