# Generated by Django 5.0.6 on 2024-07-06 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_letterhead_letterhead_path_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_allocations',
            fields=[
                ('invoice_allocations_pk', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(max_length=100, null=True)),
                ('invoice_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.invoices')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.costing')),
            ],
        ),
    ]
