# Generated by Django 5.0.6 on 2024-07-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_invoice_allocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_allocations',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoices',
            name='total_gst',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
