# Generated by Django 5.0.6 on 2024-07-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_invoice_allocations_gst_amount_invoices_total_gst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='total_cost',
            new_name='total_net',
        ),
    ]
