# Generated by Django 5.0.6 on 2024-07-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_total_cost_invoices_total_net'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='invoice_status',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
