# Generated by Django 5.0.6 on 2024-07-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_invoices_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invoice_status',
            field=models.IntegerField(default=0),
        ),
    ]
