# Generated by Django 5.0.6 on 2024-07-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_contacts_xero_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='xero_account_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
