# Generated by Django 5.0.6 on 2024-07-10 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_costing_xero_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='invoice_date',
            field=models.DateField(default=datetime.date(2024, 7, 10)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoices',
            name='invoice_due_date',
            field=models.DateField(default=datetime.date(2024, 7, 10)),
            preserve_default=False,
        ),
    ]
