from django.db import migrations

def set_default_invoice_xero_id(apps, schema_editor):
    # We can't import the Invoices model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Invoices = apps.get_model('main', 'Invoices')
    for invoice in Invoices.objects.filter(invoice_xero_id__isnull=True):
        invoice.invoice_xero_id = 'abc'  # replace with your default value
        invoice.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_invoices_invoice_xero_id'),
    ]

    operations = [
        migrations.RunPython(set_default_invoice_xero_id),
    ]# Generated by Django 5.0.6 on 2024-07-13 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_invoices_invoice_xero_id'),
    ]

    operations = [
    ]
