# Generated by Django 5.0.6 on 2024-08-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20240713_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='xero_project_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_allocations',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='quote_allocations',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
