# Generated by Django 5.0.6 on 2024-09-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_projects_xero_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='invoice_division',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
