# Generated by Django 5.0.6 on 2024-09-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_invoices_invoice_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
