# Generated by Django 5.0.6 on 2024-10-06 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_costing_fixed_on_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='HC_claims',
            fields=[
                ('hc_claim_pk', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='invoices',
            name='associated_hc_claim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hc_claims'),
        ),
    ]
