# Generated by Django 5.0.6 on 2024-10-06 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_hc_claims_display_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HC_claim_allocations',
            fields=[
                ('hc_claim_allocations_pk', models.AutoField(primary_key=True, serialize=False)),
                ('committed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uncommitted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixed_on_site', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sc_invoiced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hc_claimed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qs_claimed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hc_claim_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hc_claims')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.costing')),
            ],
        ),
    ]
