# Generated by Django 5.0.6 on 2024-10-12 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_hc_claim_allocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='hc_claim_allocations',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hc_claim_allocations',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hc_claim_allocations',
            name='contract_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hc_claim_allocations',
            name='fixed_on_site_previous',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hc_claim_allocations',
            name='fixed_on_site_this',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hc_claim_allocations',
            name='hc_claimed_previous',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hc_claim_allocations',
            name='qs_claimed_previous',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hc_claim_allocations',
            name='sc_invoiced_previous',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hc_claim_allocations',
            name='working_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
