# Generated by Django 5.0.6 on 2024-10-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_hc_claim_allocations_adjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='uncommitted_notes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
