# Generated by Django 5.0.6 on 2024-12-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_costing_uncommitted_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_allocations',
            name='allocation_type',
            field=models.IntegerField(choices=[(0, 'as per invoice_type'), (1, 'direct cost in progress claim')], default=0),
        ),
        migrations.AddField(
            model_name='invoices',
            name='invoice_type',
            field=models.IntegerField(choices=[(0, 'Progress Claim'), (1, 'Direct Cost')], default=0),
        ),
    ]
