# Generated by Django 5.0.6 on 2025-01-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_invoice_allocations_allocation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invoice_type',
            field=models.IntegerField(choices=[(2, 'Progress Claim'), (1, 'Direct Cost')], default=0),
        ),
    ]
