# Generated by Django 5.0.6 on 2025-01-26 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_invoices_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_allocations',
            name='quotes_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_allocations', to='main.quotes'),
        ),
    ]
