# Generated by Django 5.0.6 on 2025-01-26 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_quote_allocations_quotes_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_allocations',
            name='invoice_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_allocations', to='main.invoices'),
        ),
    ]
