# Generated by Django 5.0.6 on 2025-02-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_invoice_allocations_invoice_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='xero_sales_account',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
