# Generated by Django 5.0.6 on 2025-02-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_projects_xero_sales_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='checked',
            field=models.IntegerField(default=0),
        ),
    ]
