# Generated by Django 5.0.6 on 2025-02-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_hc_claims_invoicee'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE main_costing DROP COLUMN xero_account_code_mdg;',
            reverse_sql='ALTER TABLE main_costing ADD COLUMN xero_account_code_mdg character varying(100) NOT NULL DEFAULT \'\';'
        ),
    ]
