# Generated by Django 5.0.6 on 2025-02-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_remove_xero_account_code_mdg'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='invoice_category',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
