# Generated by Django 5.0.6 on 2025-02-14 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_categories_invoice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='contact_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contacts'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
