# Generated by Django 5.0.6 on 2025-03-31 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_quotes_contact_pk_alter_quotes_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variations',
            fields=[
                ('variation_pk', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(max_length=1000, null=True)),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.costing')),
            ],
        ),
    ]
