# Generated by Django 5.0.6 on 2025-05-09 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_variations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hc_variation',
            fields=[
                ('hc_variation_pk', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('claimed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hc_variation_allocations',
            fields=[
                ('hc_variation_allocation_pk', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.costing')),
                ('hc_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hc_variation')),
            ],
        ),
        migrations.DeleteModel(
            name='Variations',
        ),
    ]
