# Generated by Django 5.0.6 on 2025-05-09 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_hc_variation_hc_variation_allocations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hc_variation',
            name='number',
        ),
    ]
