# Generated by Django 5.0.6 on 2025-05-10 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_remove_hc_variation_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hc_variation',
            name='claimed',
        ),
    ]
