"""
Django settings for dev_app project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# --- Secrets ----------------------------------------------------------------
# Dev defaults below are intentionally weak / well-known and exist ONLY so a
# fresh checkout can run `manage.py runserver` without setting env vars.
# `production_aws.py` overrides every value here and refuses to boot if the
# corresponding env var is missing. Never paste a real production value into
# this file.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'dev-only-secret-key-not-for-production-use'
)

XERO_ENCRYPTION_KEY = os.environ.get(
    'XERO_ENCRYPTION_KEY',
    # Dev-only Fernet key (32 url-safe base64 bytes). Production must override.
    'TestKey-DevOnly-NOT-for-prod-AAAAAAAAAAAAAAAAAA='
)

EMAIL_API_SECRET_KEY = os.environ.get(
    'EMAIL_API_SECRET_KEY',
    'dev-only-email-api-secret-key'
)

ALLOWED_HOSTS = ['app.mason.build', '.elasticbeanstalk.com', 'localhost', '127.0.0.1']

# Diagnostics endpoints (DB wipe, secret previews, OAuth params) are off by
# default. Enable temporarily via env var when troubleshooting:
#   ENABLE_DIAGNOSTICS=1
ENABLE_DIAGNOSTICS = os.environ.get('ENABLE_DIAGNOSTICS', '').lower() in ('1', 'true', 'yes')

# CSRF trusted origins for HTTPS and local development
# Note: Django doesn't support port wildcards, so we list common dev ports
CSRF_TRUSTED_ORIGINS = [
    'https://app.mason.build',
    'https://*.elasticbeanstalk.com',
    'http://127.0.0.1:8000',
    'http://127.0.0.1:8080',
    'http://localhost:8000',
    'http://localhost:8080',
]

# For local development, also trust any origin (handled by checking DEBUG)
import sys
if 'runserver' in sys.argv or 'DEBUG' in os.environ:
    # Add dynamic port origins for local dev
    CSRF_TRUSTED_ORIGINS += [
        'http://127.0.0.1:62958',
        'http://localhost:62958',
        'http://127.0.0.1:51459',
        'http://localhost:51459',
    ]

# Trust X-Forwarded-Proto header from AWS Load Balancer
# This allows Django to detect HTTPS connections properly
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.humanize',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'construction',
]

MIDDLEWARE = [
    # SecurityMiddleware first so HSTS/SSL-redirect/header rules apply before
    # everything else (per Django's deployment checklist).
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise as early as possible so static files don't pay the cost of
    # auth/messages middleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'dev_app.middleware.CanonicalHostRedirectMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

# File upload settings - allow larger PDFs for quotes (10 MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB

ROOT_URLCONF = 'dev_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dev_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default='postgresql://dev_app_user:dev_app_password@localhost/dev_app_db', conn_max_age=600)
}

db_from_env = dj_database_url.config(conn_max_age=600)
if db_from_env:
    DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

EMAIL_BACKEND = 'dev_app.email_backends.CustomEmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Authentication settings
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

# Principal contractor identity stamped onto the NSW Subcontractor's Statement
# on the supplier-facing PO progress-claim form. Override via env in prod.
HEAD_CONTRACTOR_NAME = os.environ.get('HEAD_CONTRACTOR_NAME', '')
HEAD_CONTRACTOR_ABN = os.environ.get('HEAD_CONTRACTOR_ABN', '')

#to be deleted pre production:

